%macro STACK_START 0

    MOV RDI, RSP

    PUSH R15
    PUSH R14
    PUSH R13
    PUSH R12
    PUSH R11
    PUSH R10
    PUSH R9
    PUSH R8
    PUSH RBP
    PUSH RDI
    PUSH RSI
    PUSH RDX
    PUSH RCX
    PUSH RBX
    PUSH RAX

    CLD

%endmacro

%macro STACK_END 0

    POP RAX
    POP RBX
    POP RCX
    POP RDX
    POP RSI
    POP RDI
    POP RBP
    POP R8
    POP R9
    POP R10
    POP R11
    POP R12
    POP R13
    POP R14
    POP R15

    IRETQ

%endmacro

%macro REGISTER_INTERRUPT 2
    GLOBAL  %1
    EXTERN  %2
    %1:
        STACK_START
        call    %2
        STACK_END
%endmacro

GLOBAL LOAD_IDT
LOAD_IDT:
    LIDT    [RDI]
    STI
    RET

REGISTER_INTERRUPT  ASM_DIV_BY_ZERO, div_by_zero_i
REGISTER_INTERRUPT  ASM_BREAKPOINT, breakpoint_i
REGISTER_INTERRUPT  ASM_DOUBLE_FAULT, double_fault_i
REGISTER_INTERRUPT  ASM_GENERAL_PROTECTION, general_protection_i
REGISTER_INTERRUPT  ASM_KEYBOARD, keyboard_i
REGISTER_INTERRUPT  ASM_DEBUG, debug_i
REGISTER_INTERRUPT  ASM_INVALID_OPCODE, invalid_opcode_i
