GLOBAL CAS
CAS:
    LOCK CMPXCHG    RAX, RDI
    RET

GLOBAL LOCKED_READ
LOCKED_READ:
    LOCK XADD       RAX, RDI
    RET

GLOBAL LOCKED_WRITE
LOCKED_WRITE:
    LOCK XCHG       RAX, RDI
    RET

GLOBAL LOCKED_INCREMENT:
LOCKED_INCREMENT:
    LOCK INC        RAX, RDI
    RET

GLOBAL LOCKED_DECREMENT:
LOCKED_DECREMENT:
    LOCK DEC        RAX, RDI
    RET
